### ISSUE TITLE
add fb / tw names to account profile page

### ISSUE THREAD

**Issue by michaelsnook** [wordsandwriting/lumen#11]
we should add a space for facebook and twitter profile so people can be friends!

**Comment by wordsandwriting** [comment]
If you setup the login via Facebook/Twitter, then people can connect their accounts and they will show up on profile pages

**Comment by wordsandwriting** [comment]
Fixed by https://github.com/wordsandwriting/lumen/commit/454882458879425f523676927f6638e64864bc3c
