### ISSUE TITLE
reply-to the list, not the individual

### ISSUE THREAD

**Issue by michaelsnook** [wordsandwriting/lumen#14]
Right now, when I "reply" to a Lumen email, I get the individual user who sent it, rather than the listserv address. So then my default behavior becomes to use reply-all, which will send one email to the original poster via email, and a second message via lumen. I would much prefer to have "reply" go to the list, and just use that instead of having to manually futz with the recipients or visit the web app to avoid double-hitting people.

**Comment by wordsandwriting** [comment]
Check the REPLY_TO_GROUP config option

**Comment by michaelsnook** [comment]
Ahh, sorry, running an old version. Thanks!
