### ISSUE TITLE
preview not available, but no error message

### ISSUE THREAD

**Issue by tttp** [wordsandwriting/lumen#15]
Experiencing lumen as configured at progressivedevelopment, spotting an issue:
when you aren't a member of a group, and click on that group, you land on the discussion tab /groups/introductions#conversations-tab, with the spinner... and nothing. the spinner spins endlessly.

It works fine after you join the group (and it's a group without approval, so you can directly join)

If the user doesn't have access to the group, it's be better to have a clear message instead of a never loading page (ideally with the explanation on how to join) or a preview working (for groups that you can join without restriction at least)

Awesome tool, highly tempted to use it at wemove.eu

**Comment by wordsandwriting** [comment]
Fixed with https://github.com/wordsandwriting/lumen/commit/0aebc84338db2a36ff77b65ac551f5d6453cc07d
