### ISSUE TITLE
Let site admins use group admin tools like adding members

### ISSUE THREAD

**Issue by michaelsnook** [wordsandwriting/lumen#18]
Right now, if I want to add a person into a group where I'm not currently an admin, I have to either go into the admin and add the Membership record by hand (particularly inconvenient if the person isn't currently in the system and you also have to create their Account record), or go into the admin and make myself an admin in the group and then use the regular group administration tools to add the person to the group (particularly silly if I'm not actually meant to be a member of the group, but just doing someone a favor by adding the person).

It would be really nice if site admins (or maybe a different permissions option like "manager") could use the admin tools for each group (including seeing metrics and managing messages) without actually having to add themselves to each and every group. Basically, we only have one person on the team who really gets how the admin works and feels comfortable using it regularly, but we have 8 people who regularly engage in various administrative tasks that the existing interfaces do a pretty good job of covering.

**Comment by wordsandwriting** [comment]
Site admins can now access /groups/{slug}/manage_members without being a member https://github.com/wordsandwriting/lumen/commit/7ecdb304728ebf125944563ff550311cff671032
