### ISSUE TITLE
in-reply-to headers get binned

### ISSUE THREAD

**Issue by andylolz** [wordsandwriting/lumen#2]
This sort of thing happens all the time with Lumen in gmail:
![screen shot 2014-11-03 at 17 20 59](https://cloud.githubusercontent.com/assets/464193/4886630/f97d41f8-637d-11e4-9001-c2520b187882.png)

i.e. the same conversation gets broken into multiple threads. This makes following a discussion on gmail quite difficult.

I think gmail primarily uses the `in-reply-to` header (if it’s not present, it does it’s best using reply text, subject lines etc). This header is __not sent__ in Lumen emails. ~~This is possibly a problem with plancake, I’m not sure…~~

**Comment by louisLavery** [comment]
I'm using Lumen with PositiveMoney.org. 
As others have said, this is a pita, especially when it goes recursive!
Is this going to be fixed any time soon?

**Comment by wordsandwriting** [comment]
This was fixed some time ago - see https://github.com/wordsandwriting/lumen/blob/master/models/group.rb#L433

**Comment by louisLavery** [comment]
Hello Stephen,

On 29/03/15 22:24, Stephen Reid wrote:
> This was fixed some time ago - see https://github.com/wordsandwriting/lumen/blob/master/models/group.rb#L433


By "fixed" I guess you mean fixed the "replying above/below the line" 
feature (that is you've not implemented andylolz's algorithm).

Is the feature only visible on phones and such[1]?

Thanks, louis.


[1] I don't have a phone, post only from a laptop, and haven't seen the 
feature there.

**Comment by louisLavery** [comment]
Hello again Stephen,

Ignore my last email, just spotted the feature in an email replying to a 
post of mine on Lumen. Sorry about the noise.

Hmm, next question is, why does that reply email contain the whole 
thread, in reverse order? Or so it seems.

Regards, louis.

**Comment by louisLavery** [comment]
Oh, my earlier emails have popped up here, didn't know it worked that way.

Anyway, regards users having to start replies above a certain line. Sorry, but expecting users to obey rules that make the programmer's life easier is not on. It's the programmer's job to make it easy for users to use your software, otherwise they won't.
