### ISSUE TITLE
Can't edit users with weak passwords without changing the password

### ISSUE THREAD

**Issue by michaelsnook** [wordsandwriting/lumen#21]
I think this is new! I was trying to use the admin to add the "prevent new memberships" flag to a user who is leaving the network and being placed on restricted access. But I got the following error message:

![screenshot](https://www.evernote.com/shard/s102/sh/c27b0a77-9d03-4c1f-8a03-e99d8f5dcca1/675131d9fceeacf9/res/62a3d7f1-42f0-434a-b6a3-6cd465d883e9/skitch.png)

**Comment by wordsandwriting** [comment]
Fixed by https://github.com/wordsandwriting/lumen/commit/ce6dcc0ab240b4454e5d920257dee95c4f3a7f92
