### ISSUE TITLE
Deployment relies on commercial services

### ISSUE THREAD

**Issue by almereyda** [wordsandwriting/lumen#4]
The current deployment instructions rely heavily on the Heroku ecosystem.
The application uses proprietary Heroku add-ons and extra services.

This discourages small initiatives from deploying on own infrastructure (i.e. for privacy reasons), as it is just not possible.

We should try to formulate a way to easily deploy Lumen with Docker, for example.

**Comment by wordsandwriting** [comment]
Now documented in the README

**Comment by almereyda** [comment]
Thanks. As we have Dokku available now, I can give it a shot.

**Comment by almereyda** [comment]
@wordsandwriting Regarding the latest dokku commit, it came to my mind one could also try to write a whole guide on how to run all services seperately.

I'm especially interested in substituting

* the mail service integration with something more RESTful like https://github.com/mlandauer/cuttlefish and
* Amazon S3 with any other suitable kind of [object storage](http://meta.allmende.io/t/object-based-storage-systems/33/15), preferably those compatible with the S3 API first.

Please also note Discorse, for example, switched back from S3 static assetts to local file uploads.
