### ISSUE TITLE
Turning off emails doesn't work

### ISSUE THREAD

**Issue by louisLavery** [wordsandwriting/lumen#5]
I have turned Email Notifications off but still receive emails if the poster replies to a lumen email by email. Is this correct behaviour? Which it shouldn't be, IMO, off means off.

**Comment by wordsandwriting** [comment]
Can you provide more details? Which site are you part of?

**Comment by louisLavery** [comment]
On 06/04/15 21:59, Stephen Reid wrote:
> Can you provide more details? Which site are you part of?

Sorry, think that should have been. positiveMoney.
