### ISSUE TITLE
Email threading is fragile, might work better to use In-Reply-To/References mail headers

### ISSUE THREAD

**Issue by wu-lee** [wordsandwriting/lumen#6]
I am a user of Lumen (via http://net.positivemoney.org). I very much like that Lumen can be used like a mailing list, as I would be less likely to read and contribute to discussions if I needed to visit the site in order to do so.

However as alluded to by other users on that site, Lumen's threading mechanism is fragile. To my eyes, it is also somewhat intrusive, and I suspect unnecessary (see below).  It requires users to reply in a particular place - above text inserted by lumen instructing the user to comment above.

Threading problems arise when users do not always do this correctly, resulting in discussion threads being broken. I am not personally very suprised this happens so often, since it forces a particular style of reply that isn't natural nor normally mandated in email mailing list.  You could even argue that it goes against normal mailing list etiquette - of which admittedly there are various variations. 

  https://en.wikipedia.org/wiki/Posting_style

Speaking personally, when trying to reply in a traditional posting style, i.e. trimming and bottom-posting, it actually makes life harder for me if I want to preserve the threading; in fact I might even be breaking the threading mechanism unwittingly, I cannot really tell, and presumably nor can anyone else using email.

The current mechanism also discourages trimming of responses, resulting in enormously large nested quotations in a long discussion. Although I can't tell for sure whether these are added by the users email clients or Lumen, whichever it is: the more text inlined in an email the more places users can insert their reply and subvert the threading mechanism.

Lumen's current mail threading mechanism could be made transparent to the user.  Most mailing list software I've used handle threading without needing any manual cooperation of the participants.  The emails are sent with In-Reply-To and/or References headers, and the users' email clients handle them accordingly.

You may already be familiar with this, but in any case, here is a description of how this works:

  http://www.jwz.org/doc/threading.html
  http://cr.yp.to/immhf/thread.html

The former page references a Ruby library which might help, as it implements Jamie Zawinski's algorithm for sorting emails. I suspect you mainly just need to add the requisite headers on outgoing email, and parse them in incoming mail to assign them in a sequence.

  https://github.com/fdietz/jwz_threading

I believe using this as the threading mechanism for email would help improve Lumen's usability for email subscribers vastly.

Thanks!

**Comment by wu-lee** [comment]
One thing I should also mention: email threading of Lumen posts does not seem to work for me in Thunderbird.  The first post in a conversation has all subsequent posts as direct replies to it, i.e.

    - [group] message
        - [group] Re: message
        - [group] Re: message
        - [group] Re: message
        - [group] Re: message
        - [group] Re: message
        - [group] Re: message

There never seems to be any heirarchy, for example, I'd expect something like this:

    - [group] message
        - [group] Re: message
            - [group] Re: message
            - [group] Re: message
        - [group] Re: message
            - [group] Re: message
                - [group] Re: message
                    - [group] Re: message

It also looks like a reply in the web UI does not get threaded at all, judging by a recent one of my own.  However that may because the original was cross-posted in two groups, and my reply was only in the second.

**Comment by wordsandwriting** [comment]
Hi wu-lee, thanks for your comments. As of a couple of weeks ago, Lumen
does set the proper In Reply To and References headers, so you don't HAVE
to 'reply above this line', though text below that point is still truncated.

As you point out in your second email, Lumen doesn't support full 'tree
like' threading - this is a delibrate decision to keep things simple.

Best,
Steve

**Comment by wu-lee** [comment]
That's good news Steve, I'll pass it on and hopefully the installation may be upgraded.  Although speaking personally, the tree-threading will be missed, it reflects reality by showing who replied to what.

Thanks
