### ISSUE TITLE
Ability to create a conversation that's in multiple groups at once

### ISSUE THREAD

**Issue by michaelsnook** [wordsandwriting/lumen#8]
It would be nice if I could create a conversation thread that spanned multiple groups, without sending dual emails to people who are members of both. It would help us pick who we're sharing with more naturally and use smaller more atomic groups without necessarily fragmenting each conversation, which would seem to play to the strengths of this model of discussion-management (or at least, the way we've used the tool).

**Comment by wordsandwriting** [comment]
Perhaps the new feature to enable/disable email notifications for certain hashtags helps here?
