### ISSUE TITLE
"Request account" page?

### ISSUE THREAD

**Issue by michaelsnook** [wordsandwriting/lumen#9]
It would be good to have a page where staffers can request an account and have site admins approve access. We have a number of orgs using the discussion platform but not all staffers at each org are on the platform, so it would be nice if they (or someone else at the org) could make a request.

Related to #7 but probably simpler and less risky.

**Comment by wordsandwriting** [comment]
If you set group privacy to closed, then you'll find a request membership page at groups/{group slug}/request_membership
